# Generated by Django 5.0.3 on 2024-05-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('IDReceta', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Calorias', models.CharField(max_length=50, null=True)),
                ('Instrucciones', models.TextField(null=True)),
                ('Etiquetas', models.CharField(max_length=100, null=True)),
                ('Comentarios', models.TextField(null=True)),
                ('Valoración', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('TiempoPreparación', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
