# Generated by Django 5.0.3 on 2024-05-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='CarbHidratos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Grasas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Ingredientes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Proteinas',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
