# Generated by Django 5.0.3 on 2024-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0002_recipe_carbhidratos_recipe_grasas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('IDUsuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Genero', models.TextField(max_length=50, null=True)),
                ('Alergias', models.TextField(max_length=100, null=True)),
                ('Nombre', models.TextField(max_length=80, null=True)),
                ('Correo', models.TextField(max_length=100)),
                ('Password', models.TextField(max_length=100)),
            ],
        ),
    ]
