# Generated by Django 5.0.3 on 2024-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='IDReceta',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Correo',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='IDUsuario',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
