# Generated by Django 5.0.3 on 2024-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0005_ingredient_tag_remove_recipe_etiquetas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Etiquetas',
            field=models.ManyToManyField(through='MRFY.RecipeTag', to='MRFY.tag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Ingredientes',
            field=models.ManyToManyField(through='MRFY.RecipeIngredient', to='MRFY.ingredient'),
        ),
    ]
