# Generated by Django 5.0.3 on 2024-05-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0006_recipe_etiquetas_recipe_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Imagen',
            field=models.TextField(default='images/wallpaper4.jpg'),
        ),
    ]
