# Generated by Django 5.0.3 on 2024-05-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0007_alter_recipe_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('IDUsuario', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Genero', models.TextField(max_length=50, null=True)),
                ('Alergias', models.TextField(max_length=100, null=True)),
                ('Nombre', models.TextField(max_length=80, null=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('password', models.TextField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
