# Generated by Django 5.0.3 on 2024-05-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0011_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
