# Generated by Django 5.0.3 on 2024-05-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0013_shoppinglist_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
