# Generated by Django 5.0.3 on 2024-05-13 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0014_alter_recipeingredient_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='IDIngrediente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MRFY.ingredient'),
        ),
    ]
