# Generated by Django 5.0.3 on 2024-05-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0015_shoppinglistitem_idingrediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='Cantidad',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
