# Generated by Django 5.0.3 on 2024-05-14 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0016_alter_recipeingredient_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='FechaCreación',
            field=models.DateTimeField(default=None),
        ),
    ]
