# Generated by Django 5.0.3 on 2024-05-14 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0017_recipe_autor_recipe_fechacreación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='FechaCreación',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
