# Generated by Django 5.0.3 on 2024-05-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0018_alter_recipe_autor_alter_recipe_fechacreación'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Verificado',
            field=models.BooleanField(default=False),
        ),
    ]
