# Generated by Django 5.0.3 on 2024-05-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0019_recipe_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Imagen',
            field=models.ImageField(default='images/wallpaper4.jpg', upload_to='images/'),
        ),
    ]
