# Generated by Django 5.0.3 on 2024-05-16 18:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0020_alter_recipe_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Instrucciones',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
