# Generated by Django 5.0.3 on 2024-05-16 19:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0022_alter_recipe_instrucciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Instrucciones',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
    ]
