# Generated by Django 5.0.3 on 2024-05-16 19:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MRFY', '0023_alter_recipe_instrucciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Instrucciones',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
